/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rs.ac.bg.fon.ps.view.form;

import javax.swing.JDialog;
import javax.swing.JFrame;
import rs.ac.bg.fon.ps.view.form.util.FormMode;

/**
 *
 * @author Korisnik
 */
public class FrmMain extends javax.swing.JFrame {

    /**
     * Creates new form FrmMain
     */
    public FrmMain() {
        super("Main form");
        initComponents();
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jmenuBarMain = new javax.swing.JMenuBar();
        jmenuShowpiece = new javax.swing.JMenu();
        jmiShowpieceNew = new javax.swing.JMenuItem();
        jmiShowpieceShowAll = new javax.swing.JMenuItem();
        jmenuAbout = new javax.swing.JMenu();
        jmiAboutSoftware = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jmenuShowpiece.setText("Showpiece");

        jmiShowpieceNew.setText("New");
        jmiShowpieceNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiShowpieceNewActionPerformed(evt);
            }
        });
        jmenuShowpiece.add(jmiShowpieceNew);

        jmiShowpieceShowAll.setText("Show all");
        jmiShowpieceShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmiShowpieceShowAllActionPerformed(evt);
            }
        });
        jmenuShowpiece.add(jmiShowpieceShowAll);

        jmenuBarMain.add(jmenuShowpiece);

        jmenuAbout.setText("About");

        jmiAboutSoftware.setText("Software");
        jmenuAbout.add(jmiAboutSoftware);

        jmenuBarMain.add(jmenuAbout);

        setJMenuBar(jmenuBarMain);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jmiShowpieceNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiShowpieceNewActionPerformed
        JDialog frmShowpiece = new FrmShowpiece(this, true, FormMode.FORM_ADD);
        frmShowpiece.setVisible(true);
    }//GEN-LAST:event_jmiShowpieceNewActionPerformed

    private void jmiShowpieceShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmiShowpieceShowAllActionPerformed
        new FrmViewShowpieces(this, true).setVisible(true);
    }//GEN-LAST:event_jmiShowpieceShowAllActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jmenuAbout;
    private javax.swing.JMenuBar jmenuBarMain;
    private javax.swing.JMenu jmenuShowpiece;
    private javax.swing.JMenuItem jmiAboutSoftware;
    private javax.swing.JMenuItem jmiShowpieceNew;
    private javax.swing.JMenuItem jmiShowpieceShowAll;
    // End of variables declaration//GEN-END:variables
}
